# Generated by Django 5.2.4 on 2025-08-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('desc', models.TextField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='user_cred',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user_cred',
            old_name='username',
            new_name='Username',
        ),
    ]
